### ISSUE TITLE
Fatal error: Uncaught Error: Failed opening required 'reflect/core/src/Controller.php' (include_path='.') in index.php on line 14

### ISSUE THREAD

**Issue by zpcol** [davidgoy/reflect#1]
on file index.php
before:
`require_once __DIR__ . '/../reflect/core/src/Controller.php';`

after fix
`require_once __DIR__ . '../reflect/core/src/Controller.php';`

**Comment by davidgoy** [comment]
Thanks for your feedback.

1. What web server are you using?

2. How does your directory structure look like for your Reflect site? I needs to look like this...

```text
(your domain name e.g. example.com)/
├─ reflect/
└─ (your document root. e.g. public_html)/
        ├ index.php
        ├ css/
        ├ js/
        ├ .htaccess
```
Cheers!

**Comment by zpcol** [comment]
i'm use openserver

```
(folder install)/
├─ (domains)/
└─ reflect/
└─ my-domain.com/
        ├ index.php
        ├ css/
        ├ js/
        ├ .htaccess
└─ modules
        ├ memcached
        ├ heidisql
```

**Comment by zpcol** [comment]
i'm use openserver

`
(folder install)/
├─ (domains)/
└─ reflect/
└─ my-domain.com/
        ├ index.php
        ├ css/
        ├ js/
        ├ .htaccess
└─ modules
        ├ memcached
        ├ heidisql
`

**Comment by davidgoy** [comment]
In regards to line 14 on index.php:

``` text
require_once __DIR__ . '/../reflect/core/src/Controller.php';
```

The preceding '/' indicates an absolute path starting from the document root.

So based on the error you encountered, it seems like 'my-domain.com/' is not actually your document root. This could be due to your web server's virtual host configuration.

Try replacing line 14 on index.php with this:

``` text
require_once $_SERVER['DOCUMENT_ROOT'] . '/../reflect/core/src/Controller.php';
```

Does that work for you now? 

If that does not work, then this probably means that 'my-domain.com/' is indeed not your document root.

**Comment by davidgoy** [comment]
Make sure that index.php sits inside your document root.

Your directory structure should look something like this:

```text
(your domain name e.g. example.com)/
├─ reflect/
└─ (your document root. e.g. public_html)/
        ├ index.php
        ├ css/
        ├ js/
        ├ .htaccess
```

Also make sure that the folder you think is your document is ACTUALLY your document root.
